version: '2'
services:
    loginapp-app:
        image: loginapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://loginapp-mysql:3306/loginapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    loginapp-mysql:
        extends:
            file: mysql.yml
            service: loginapp-mysql
